version: '3.7'

services:
  fdxchangebe:
    image: fdxchangebe
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
